from tasks.x15_task_handle_error_callback import run_task


def run():
    run_task()
